apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: db-glpi
    image: docker.io/library/mariadb:11.8
    envFrom:
      - configMapRef:
          name: db-glpi
      - secretRef:
          name: db-glpi
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: db-glpi-pv
        readOnly: false
    ports:
      - containerPort: 3306

  volumes:
    - name: db-glpi-pv
      persistentVolumeClaim:
        claimName: db-glpi-pvc