apiVersion: v1
kind: Secret
metadata:
  name: glpi
  namespace: 
type: Opaque
stringData:
  GLPI_DB_PASSWORD: "cGFzc3dvcmQ="
  GLPI_API_USER_TOKEN: ""
  GLPI_API_APP_TOKEN: ""
  GLPI_LOGIN_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: db-glpi
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "cm9vdA=="
  MARIADB_PASSWORD: "cGFzc3dvcmQ="
