name: CI

on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Print repo info
        run: |
          echo "This work on a self-hosted docker container"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor:  ${{ github.actor }}"
